In [1]:
import jax.numpy as np
from jax import grad, jit, vmap
from jax import random
from jax import lax

# another `fori_loop` test

In [81]:
def update_fun(i, lis):
    lis.append(i)
    del lis[0]
    return lis

lax.fori_loop(0, 10, update_fun, [1, 2, 3])

[DeviceArray(7, dtype=int32),
 DeviceArray(8, dtype=int32),
 DeviceArray(9, dtype=int32)]

In [83]:
python_fori_loop(0, 10, update_fun, [1,2,3])

[7, 8, 9]

# `lax.scan`

Rough python equivalent:    

In [34]:
def scan(f, init, xs, length=None):
    if xs is None:
        xs = [None] * length
    carry = init
    ys = []
    for x in xs:
        carry, y = f(carry, x)
        ys.append(y)
    return carry, np.stack(ys)

Can we define `fori_loop` in terms of `scan`? Code taken from a github issue:

In [48]:
from jax import lax

In [49]:
def differentiable_fori_loop(lower, upper, body_fun, init_val):
    f = lambda x, i: (body_fun(i, x), ())
    result, _ = lax.scan(f, init_val, np.arange(lower, upper))
    return result

In [71]:
def python_fori_loop(lower, upper, body_fun, init_val):
    val = init_val
    for i in range(lower, upper):
        val = body_fun(i, val)
    return val

test:

In [51]:
f = lambda i, x: x**2 + i

In [56]:
lax.fori_loop(0, 3, f, 1)

DeviceArray(6, dtype=int32)

In [59]:
python_fori_loop(0, 3, f, 1)

6

In [58]:
differentiable_fori_loop(0, 3, f, 1)

DeviceArray(6, dtype=int32)

# fori loop

In [2]:
from jax.lax import fori_loop

In [3]:
a = 1

In [6]:
@jit
def test(L):
    return fori_loop(0, L, lambda i, n: n+1, 1)

In [7]:
test(10)

DeviceArray(11, dtype=int32)

Compare a normal for loop, where we cant `jit` the function:

In [10]:
# @jit
def test2(L):
    x = 1 # init_val
    for _ in range(L):
        x = x + 1
    return x

In [11]:
test2(10)

11

### using `grad` with `fori_loop`

In [21]:
def test3(x):
    """output x^4 using fori loop to compute"""
    return fori_loop(0, 2, lambda i, y: y*y, x)

In [25]:
test3(3.)

DeviceArray(81., dtype=float32)

In [26]:
grad(test3)(3.)

AssertionError: 

In [33]:
from jax import jacfwd
jacfwd(test3)(3.) # 4*x^3 = 4 * 27 = 108

DeviceArray(108., dtype=float32)

# gpu vs cpu

In [2]:
from jax.lib import xla_bridge
backend = xla_bridge.get_backend().platform
print(xla_bridge.get_backend().platform)

cpu


/home/lauro/.virtualenvs/msc-thesis/lib/python3.6/site-packages/jax/lib/xla_bridge.py:122: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


In [3]:
key = random.PRNGKey(0)
d = 10000
x = random.normal(key, shape=(d, d))
key = random.split(key, 1)[0]
y = random.normal(key, shape=(d, d))

In [4]:
print(f"Running on {backend}.")
print()
%timeit np.matmul(x, y).block_until_ready()

Running on cpu.



KeyboardInterrupt: 

## `np.sort`

In [5]:
x = np.array([[2,3,4],
              [3,2,1]])
print(x.shape)
np.sort(x)

(2, 3)


DeviceArray([[2, 3, 4],
             [1, 2, 3]], dtype=int32)

In [4]:
np.sort(x, axis=0)

DeviceArray([[2, 2, 1],
             [3, 3, 4]], dtype=int32)

In [6]:
np.sort(x, axis=1)

DeviceArray([[2, 3, 4],
             [1, 2, 3]], dtype=int32)

# can `jit` take care of this?

In [7]:
batched_vdot = vmap(np.vdot)

In [22]:
def test(x, y):
    """
    do a lot of useless repetitive stuff. return np.vdot(x, y)
    """
    n = 2 * 10**6
    xtiled = np.tile(x, (n, 1))
    ytiled = np.tile(y, (n, 1))
    out = batched_vdot(xtiled, ytiled)
    return out[0]

jt = jit(test)

In [9]:
x = np.array([1,1,1])
y = np.array([1,2,3])

In [18]:
%timeit test(x, y)

1.42 s ± 73.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


%timeit jt(x, y).block_until_ready()

jup, it can

In [13]:
def quicktest(x, y):
    n = 2
    xtiled = np.tile(x, (n, 1))
    ytiled = np.tile(y, (n, 1))
    out = batched_vdot(xtiled, ytiled)
    return out[0]

qjt = jit(quicktest)

In [20]:
%timeit quicktest(x, y)

5.04 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%timeit qjt(x, y).block_until_ready()

136 µs ± 7.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## kernel computation

In [ ]:
from utils import single_rbf, ard
for x in np.linspace(-10, 10, 30):
    x = np.array([x])
    for y in np.linspace(-10, 10, 30):
        y = np.array([y])
        for h in np.linspace(1, 100, 5):
#             print("x = ", x)
#             print("y = ", y)
#             print()
#             print("rbf(x, y): ", single_rbf(x, y, h))
#             print("ard(x, y): ", ard(x, y, h))
#             print()
#             print("-----------")
            assert single_rbf(x, y, h) == ard(x, y, h)

## misc jax:

In [ ]:
key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

In [ ]:
# multiply matrices
size = 3000
x = random.normal(key, (size, size), dtype=np.float32)
%timeit np.dot(x, x.T).block_until_ready()  # runs on the GPU

In [ ]:
import numpy as onp  # original CPU-backed NumPy
x = onp.random.normal(size=(size, size)).astype(onp.float32)
%timeit np.dot(x, x.T).block_until_ready()

In [ ]:
from jax import device_put

x = onp.random.normal(size=(size, size)).astype(onp.float32)
x = device_put(x)
%timeit np.dot(x, x.T).block_until_ready()

Using `jit`

In [ ]:
def selu(x, alpha=1.67, lmbda=1.05):
    return lmbda * np.where(x > 0, x, alpha * np.exp(x) - alpha)

x = random.normal(key, (1000000,))
%timeit selu(x).block_until_ready()

In [ ]:
selu_jit = jit(selu)
%timeit selu_jit(x).block_until_ready()

take diff


In [ ]:
@jit
def sum_logistic(x):
    return np.sum(1.0 / (1.0 + np.exp(-x)))

x = np.arange(3.)
print(sum_logistic(x))
print(grad(sum_logistic)(x))

In [ ]:
x = random.normal(key, (10, 3))
batched_sum = vmap(sum_logistic)
batched_sum(x)

In [ ]:
def test(x, y):
    return np.sum(x**2 + y**2)

In [ ]:
x, y  = [random.normal(key, (10,3)), random.normal(key + 1, (10,3))]
print('single argument:', test(x[0], y[0]), '\n')
print('batch output shape:', vmap(test)(x, y).shape)
print('batch output:', vmap(test)(x, y))

In [ ]:
np.append(np.array([1,2,3]), 4)

# pytorch distance matrix

In [ ]:
import torch

In [ ]:
x = torch.rand(10, 2)
x

In [ ]:
x.split(1)

In [ ]:
row = x.split(1)[0]
row

In [ ]:
r_v = row.expand_as(x)
r_v

In [ ]:
sq_dist = torch.sum((r_v - x) ** 2, 1)
print(sq_dist.shape)
sq_dist

In [ ]:
sq_dist.view(1, -1).shape

In [ ]:
def row_pairwise_distances(x, y=None, dist_mat=None):
    if y is None:
        y = x
    if dist_mat is None:
        dtype = x.data.type()
        dist_mat = Variable(torch.Tensor(x.size()[0], y.size()[0]).type(dtype))

    for i, row in enumerate(x.split(1)):
        r_v = row.expand_as(y)
        sq_dist = torch.sum((r_v - y) ** 2, 1)
        dist_mat[i] = sq_dist.view(1, -1)
    return dist_mat

# random stuff

## first question
does `jit` cache results if it needs them again? that is, does it skip over repeated computations?

In [ ]:
import jax.numpy as np
from jax import grad, jit, vmap
from jax import random

In [ ]:
m = 10**4
def h(x):
    for i in range(m):
        x += i
    return x

In [ ]:
h(2)

In [ ]:
def f1(x):
    """
    computation of h is repeated needlessly
    """
    out = 0
    for i in range(10):
        out += h(x) + i
    return out

In [ ]:
def f2(x):
    """
    h(x) is computed only once
    """
    out = 0
    hx = h(x)
    for i in range(10):
        out += hx + i
    return out

In [ ]:
s = 4

In [ ]:
assert f1(s) == f2(s)

In [ ]:
%timeit f1(s)
%timeit f2(s)
%timeit jit(f1)(s).block_until_ready()
%timeit jit(f2)(s).block_until_ready()

## next question:
does `lax.fori_loop` compile more quickly?

In [ ]:
from jax import lax

In [ ]:
m = 10**4
s = 4

In [ ]:
def h1(x):
    body = lambda i, val: val + i
    for i in range(m):
        x = body(i, x)
    return x

In [ ]:
def h2(x):
    body = lambda i, val: val + i
    return lax.fori_loop(0, m, body, init_val=x)

In [ ]:
jit(h1)(s)

In [ ]:
jit(h2)(s)

yeees, it does!

## Next question:
when we use `lax.fori_loop`, do we get the same speedup for repeated computations?

In [ ]:
assert h(s) == h1(s)

In [ ]:
# now we use the lax fori loop h1
def f1_lax(x):
    """
    computation of h is repeated needlessly
    """
    out = 0
#     for i in range(10):
#         out += h1(x) + i
        
    out = lax.fori_loop(0, 10, lambda i, val: val + h1(x) + i, init_val=out)
    return out

def f2_lax(x):
    """
    h(x) is computed only once
    """
    out = 0
    hx = h1(x)
#     for i in range(10):
#         out += hx + i
        
    out = lax.fori_loop(0, 10, lambda i, val: val + hx + i, init_val=out)
    return out

In [ ]:
assert f1_lax(s) == f1(s)
assert f2_lax(s) == f2(s)
assert f1(s) == f2(s)

In [ ]:
# still compiles fast:
jit(f1_lax)(s)

In [ ]:
%timeit f1_lax(s)
%timeit f2_lax(s)
%timeit jit(f1_lax)(s).block_until_ready()
%timeit jit(f2_lax)(s).block_until_ready()

we do indeed have a speedup.

## How to plot 3D

In [ ]:
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

In [ ]:
# Make data.
X = np.linspace(-5, 5, 50)
Y = np.linspace(-5, 5, 50)
X, Y = np.meshgrid(X, Y) # both shape (40, 40)

Z = X**2 + Y**2

# plot
fig = plt.figure()
ax = fig.gca(projection='3d')

surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)